spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/midas_core
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: risk-validation-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.midas.pipeline.Transaction
    listener:
      type: batch